In [1]:
import pandas as pd

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

In [2]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [4]:
df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [5]:
df.shape

(1000, 12)

In [6]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [7]:
missing = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage' : round(df.isnull().sum()/len(df)*100,2)
})

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['City'].nunique()

8

In [10]:
df['Product'].nunique()

6

In [11]:
df['Order_ID'].nunique()

992

In [12]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [13]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [14]:
df.dtypes

Order_ID                 object
Order_Date       datetime64[ns]
Customer_ID              object
Customer_Name            object
Age                     float64
Gender                   object
City                     object
Product                  object
Category                 object
Quantity                  int64
Unit_Price              float64
Total_Sales             float64
dtype: object

In [15]:
df['Order_Date'].dt.month
df['Order_Date'].dt.year
df['Order_Date'].dt.quarter

0      1
1      4
2      2
3      4
4      4
      ..
995    4
996    3
997    3
998    1
999    2
Name: Order_Date, Length: 1000, dtype: int32

In [16]:
df['Calculated_Sales'] = round((df['Quantity'] * df['Unit_Price']), 2)

In [17]:
df['Difference'] = round((df['Total_Sales']- df['Calculated_Sales']), 2)

In [18]:
(df['Difference'] != 0).sum()

np.int64(0)

In [19]:
numeric_cols = ['Age', 'Quantity', 'Unit_Price', 'Total_Sales']

for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print(f"{col}: {len(outliers)} outliers")

Age: 0 outliers
Quantity: 0 outliers
Unit_Price: 0 outliers
Total_Sales: 19 outliers

In [ ]:
# Till now i have done Data analyzation process now moving to the data clenaing process

In [20]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [21]:
df['Age'].isnull().sum()

np.int64(0)

In [22]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [23]:
df['City'].isnull().sum()

np.int64(0)

In [24]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
Product             0
Category            0
Quantity            0
Unit_Price          0
Total_Sales         0
Calculated_Sales    0
Difference          0
dtype: int64

In [25]:
df['Month'] = df['Order_Date'].dt.month_name()

In [26]:
df['Quarter'] = df['Order_Date'].dt.quarter

In [27]:
df['Year'] = df['Order_Date'].dt.year

In [28]:
bins = [17,30,45,60,70]

labels = [
    'Young Adult',
    'Adult',
    'Middle Age',
    'Senior'
]

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=bins,
    labels=labels
)

In [43]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Calculated_Sales,Difference,Month,Quarter,Year,Age_Group
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,19808.39,0.0,February,1,2025,Young Adult
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,139530.80,0.0,October,4,2025,Senior
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,299928.48,0.0,May,2,2025,Senior
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,256872.24,0.0,December,4,2025,Senior
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,140365.90,0.0,November,4,2025,Adult

In [29]:
df.to_excel("Cleaned_Sales_Dataset.xlsx", index=False)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   object
 1   Order_Date        1000 non-null   datetime64[ns]
 2   Customer_ID       1000 non-null   object
 3   Customer_Name     1000 non-null   object
 4   Age               1000 non-null   float64
 5   Gender            1000 non-null   object
 6   City              1000 non-null   object
 7   Product           1000 non-null   object
 8   Category          1000 non-null   object
 9   Quantity          1000 non-null   int64
 10  Unit_Price        1000 non-null   float64
 11  Total_Sales       1000 non-null   float64
 12  Calculated_Sales  1000 non-null   float64
 13  Difference        1000 non-null   float64
 14  Month             1000 non-null   object
 15  Quarter           1000 non-null   int32
 16  Year              1000 non-null   int32
 17  Age_Group         1000 non-null   category
dtypes: category(1), datetime64[ns](1), float64(5), int32(2), int64(1), object(8)
memory usage: 126.3+ KB